#!/bin/bash

# OpenFOAM install directory
FOAM_INST_DIR=${HOME}/OpenFOAM

unset DOWNLOAD_ONLY

# Number of processors
case `hostname` in
    ff[0-9]*)
	WM_NCOMPPROCS=1
	;;
    *)
	if [ -r /proc/cpuinfo ]
	then
	    WM_NCOMPPROCS=$(egrep "^processor" /proc/cpuinfo | wc -l)
	else
	    WM_NCOMPPROCS=1
	fi
	;;
esac	
echo "WM_NCOMPPROCS= $WM_NCOMPPROCS"
export WM_NCOMPPROCS

# OpenFOAM version list to install
OpenFOAM_BUILD_OPTION_LIST=(
    OpenFOAM_VERSION=OpenFOAM-v1612+,COMPILER_TYPE=ThirdParty,COMPILER=Gcc4_8_5,COMPILE_OPTION=Opt,ARCH_OPTION=64,PRECISION_OPTION=DP,LABEL_SIZE=32,MPLIB=SYSTEMOPENMPI,BUILD_PARAVIEW=0,BUILD_FOAMY_HEX_MESH=0
)

