#!/bin/bash

# OpenFOAM install directory
FOAM_INST_DIR=/lustre/$(id -gn)/$(id -un)/OpenFOAM

unset DOWNLOAD_ONLY

# Number of processors
case `hostname` in
    reedbush-u[0-9]*)
	WM_NCOMPPROCS=1
	;;
    *)
	WM_NCOMPPROCS=36
	;;
esac
export WM_NCOMPPROCS

# OpenFOAM version list to install
OpenFOAM_BUILD_OPTION_LIST=(
OpenFOAM_VERSION=OpenFOAM-v1612+,COMPILER_TYPE=system,COMPILER=Icc17_0_1_132,COMPILE_OPTION=Opt,ARCH_OPTION=64,PRECISION_OPTION=DP,LABEL_SIZE=32,MPLIB=INTELMPI2017_1_132,BUILD_PARAVIEW=0,BUILD_FOAMY_HEX_MESH=0
)

