#!/bin/sh

module purge
module load pbsutils

case $COMPILER_TYPE in
    ThirdParty)
	;;
    system)
	case "$COMPILER" in
	    Gcc4_8_5)
		# system default version
		;;
	    Gcc*)
		version=${COMPILER#Gcc}
		version=${version//_/.}
		module load gnu/gcc_$version
		;;
	    Icc*)
		version=${COMPILER#Icc}
		version=${version//_/.}
		module load intel/$version
		;;
	    *)
		;;
	esac	
	;;
    *)
	;;
esac

case $MPLIB in
    SYSTEMOPENMPI*)
	version=${MPLIB#SYSTEMOPENMPI}
	version=${version//_/.}
	case "$COMPILER" in
	    Gcc*)
		module load openmpi/mxm/$version/gnu
		;;
	    Icc*)
		module load openmpi/mxm/$version/intel
		;;
	esac	
	;;
    SGIMPI*)
	version=${MPLIB#SGIMPI}
	version=${version//_/.}
	module load mpt/$version
	;;
    INTELMPI*)
	version=${MPLIB#INTELMPI}
	version=${version//_/.}
	module load intel-mpi/$version
	;;
    MPIMVAPICH2*)
	version=${MPLIB#MPIMVAPICH}
	version=${version//_/.}
	case "$COMPILER" in
	    Gcc*)
		module load mvapich2/mxm/$version/gnu
		;;
	    Icc*)
		module load mvapich2/mxm/$version/intel
		;;
	esac	
	MPI_ROOT=`which mpicc`
	export MPI_ROOT=${MPI_ROOT/\/bin\/mpicc/}
	;;
    HPCXMPI*)
	version=${MPLIB#HPCXMPI}
	version=${version//_/.}
	case "$COMPILER" in
	    Gcc*)
		module load hpcx/$version/gnu
		;;
	    Icc*)
		module load hpcx/$version/intel
		;;
	esac	
	export MPI_ROOT=$MPI_HOME
	;;
    *)
	;;
esac

case $MPLIB in
    INTELMPI*)
	export MPI_ROOT=$I_MPI_ROOT
	;;
esac
