#!/bin/bash

unset DOWNLOAD_ONLY

# Node switch
case `hostname -A` in
    ofp[0-9]*.jcahpc.jp*)
	# Login node
	WM_NCOMPPROCS=1
	DOWNLOAD_ONLY=yes
	;;
    ofp[0-9]*.ofp*)
	# Prepost node
	export HOME=/work/$(id -gn)/$(id -un)
	WM_NCOMPPROCS=28
	;;
    *)
	# Batch node
	export HOME=/work/$(id -gn)/$(id -un)
	WM_NCOMPPROCS=64
	;;
esac
export WM_NCOMPPROCS

# OpenFOAM install directory
FOAM_INST_DIR=${HOME}/OpenFOAM

# OpenFOAM version list to install
OpenFOAM_BUILD_OPTION_LIST=(
OpenFOAM_VERSION=OpenFOAM-v1612+,COMPILER_TYPE=system,COMPILER=Icc2017_4_196,COMPILE_OPTION=Opt,ARCH_OPTION=64,PRECISION_OPTION=DP,LABEL_SIZE=32,MPLIB=INTELMPI2017_3_196,BUILD_PARAVIEW=0,BUILD_FOAMY_HEX_MESH=0
)
