#!/bin/sh

module purge

case $COMPILER_TYPE in
    ThirdParty)
	;;
    system)
	case "$COMPILER" in
	    Gcc*)
		version=${COMPILER#Gcc}
		version=${version//_/.}
		module load gcc/$version
		;;
	    Icc*)
		version=${COMPILER#Icc}
		version=${version%KNL}
		version=${version//_/.}
		module load intel/$version
		;;
	    *)
		;;
	esac	
	;;
    *)
	;;
esac

module unload impi

case $MPLIB in
    INTELMPI*)
	version=${MPLIB#INTELMPI}
	version=${version//_/.}
	module load impi/$version
	;;
    *)
	;;
esac

case $MPLIB in
    INTELMPI*)
	export MPI_ROOT=$I_MPI_ROOT
	;;
esac
